// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5dp80JyfUzsIRA5lrNmGF7CkZfYoSMLM',
    appId: '1:175643253769:web:db923126e885e6680fecd8',
    messagingSenderId: '175643253769',
    projectId: 'gallery-app-fa590',
    authDomain: 'gallery-app-fa590.firebaseapp.com',
    storageBucket: 'gallery-app-fa590.appspot.com',
    measurementId: 'G-4G0CE8ZMHY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2zVlgEuHhxNvCzTZyrfKSryWGVUUKe80',
    appId: '1:175643253769:android:2abcd2fe3cefc3d90fecd8',
    messagingSenderId: '175643253769',
    projectId: 'gallery-app-fa590',
    storageBucket: 'gallery-app-fa590.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3P5qrzPSOkpdP8NxwenzQk_llSytmoS0',
    appId: '1:175643253769:ios:2d614ead1a52d9a00fecd8',
    messagingSenderId: '175643253769',
    projectId: 'gallery-app-fa590',
    storageBucket: 'gallery-app-fa590.appspot.com',
    iosClientId:
        '175643253769-45csfk7ms28guspcvbsmui4k9qht48ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.galleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3P5qrzPSOkpdP8NxwenzQk_llSytmoS0',
    appId: '1:175643253769:ios:2d614ead1a52d9a00fecd8',
    messagingSenderId: '175643253769',
    projectId: 'gallery-app-fa590',
    storageBucket: 'gallery-app-fa590.appspot.com',
    iosClientId:
        '175643253769-45csfk7ms28guspcvbsmui4k9qht48ar.apps.googleusercontent.com',
    iosBundleId: 'com.example.galleryApp',
  );
}
